# Generated by Django 3.1.4 on 2020-12-03 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_list',
            name='owes',
        ),
        migrations.CreateModel(
            name='owes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sachin', models.IntegerField(default=None)),
                ('rahul', models.IntegerField(default=None)),
                ('deepak', models.IntegerField(default=None)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_app.users_list')),
            ],
        ),
        migrations.CreateModel(
            name='owed_by',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sachin', models.IntegerField(default=None)),
                ('rohit', models.IntegerField(default=None)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_app.users_list')),
            ],
        ),
    ]
